language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-veronica-spa' ]; then cd .. && eval "mv $currentfolder generator-veronica-spa" && cd generator-veronica-spa; fi

